//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XFProject.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhotoUser
    {
        public int PhotoUserID { get; set; }
        public System.Guid PhotoID { get; set; }
        public string PhotoTitle { get; set; }
        public string PhotoName { get; set; }
        public string PhotoDescription { get; set; }
        public string NickNameAutor { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string PathUrl { get; set; }
        public string Email { get; set; }
    }
}
